name: 'Get Release Texts'
description: 'Generates lowercase repo name'
outputs:
  repo_lowercase:
    description: "The lowercase repository name"
    value: ${{ steps.release_texts.outputs.repo_lowercase }}
runs:
  using: "composite"
  steps:
    - name: Create a valid release tag and other text outputs
      id: release_texts
      shell: bash
      run: |
        echo "repo_lowercase=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT;
