name: 'Get Release Texts'
description: 'Generates release tag and lowercase repo name'
outputs:
  tag:
    description: "The release tag"
    value: ${{ steps.release_texts.outputs.tag }}
  repo_lowercase:
    description: "The lowercase repository name"
    value: ${{ steps.release_texts.outputs.repo_lowercase }}
runs:
  using: "composite"
  steps:
    - name: Create a valid release tag and other text outputs
      id: release_texts
      shell: bash
      run: |
        string=${{ github.ref }};
        cleaned_string="${string#refs/tags/}";
        cleaned_string="${cleaned_string#refs/heads/}";
        echo "tag=$cleaned_string" >> $GITHUB_OUTPUT;
        echo "repo_lowercase=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT;
