flowchart LR
    %% Direct Control vs WebUI+Coordinator Comparison

    %% Clients (work everywhere)
    subgraph clients["Clients"]
        webui@{ shape: circle, label: "**WebUI**" }
        client@{ shape: docs, label: "Client (Script)" }  
        %% Invisible link, otherwise direction doesn't do anything... mermaid is kinda a mess
        webui ~~~ client
    end

    %% LAN Components
    subgraph lan["**LAN**"]
        subgraph controller["Controller"]
            direct_control@{ shape: docs, label: "Direct Control Script" }
            coordinator@{ shape: div-proc, label: "Coordinator" }
        end
        host@{ shape: div-proc, label: "Host" }
    end

    %% Relationships
    clients --> |"**control**"| coordinator
    controller --> |"**startup**"| host
    controller --> |"**shutdown**"| host
    clients -.-> |"control *outside* of **LAN**"| host

    class lan lan
    class webui webui
    class coordinator coordinator
    class direct_control direct_control
    class host host
