[server]
port = 8081
bind = "127.0.0.1"

[server.auth.external]
exceptions_version = 1

[hosts]
host1 = { ip = "192.168.1.10", mac = "AA:BB:CC:DD:EE:FF", port = 9000, shared_secret = "hostsecret1" }
host2 = { ip = "192.168.1.11", mac = "AA:BB:CC:DD:EE:00", port = 9001, shared_secret = "hostsecret2" }

[clients]
client1 = { shared_secret = "clientsecret1" }
client2 = { shared_secret = "clientsecret2" }
