FROM rust:alpine

RUN apk add --no-cache npm

COPY . /src
WORKDIR /src

RUN cargo build --release --bin shuthost_host_agent --target x86_64-unknown-linux-musl
RUN cargo build --release --bin shuthost_coordinator --target x86_64-unknown-linux-musl --features=include_linux_musl_x86_64_agent