[package]
name = "agent"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
hex = "0.4.3"
hmac.workspace = true
serde.workspace = true
sha2.workspace = true
toml.workspace = true
